version: "3"
name: ollama-inference
services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /ollama:/root/.ollama
    runtime: nvidia
